version: "3.9"

services:
  build-backend:
    build: backend
    environment:
      - PORT=9090
      - debug=False
    volumes:
      - ./backend/:/usr/src/backend
    ports:
      - 9090:9090
  build-frontend:
    build: frontend
    volumes:
      - ./frontend/:/usr/src/frontend
    ports:
      - 3031:3000
