version: "3.9"

services:
  dev-backend:
    build: backend
    environment:
      - PORT=9090
      - debug=True
    volumes:
      - ./backend/:/usr/src/backend
    ports:
      - 9090:9090
  dev-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/:/usr/src/frontend
    ports:
      - 3031:3000
